services:
  frontend:
    container_name: frontend
    build: "./frontend"
    ports:
      - "4040:4040"
    environment:
      - REACT_APP_AUTH0_DOMAIN=
      - REACT_APP_AUTH0_CLIENT_ID=
      - REACT_APP_AUTH0_AUDIENCE=
      - REACT_APP_AUTH0_CALLBACK_URL=http://localhost:4040/callback
      - REACT_APP_API_SERVER_URL=http://localhost:6060
    networks:
      - authzero

  backend:
    container_name: backend
    build: "./backend"
    ports:
      - "6060:6060"
    environment:
      - PORT=6060
      - OKTA_OAUTH2_ISSUER=
      - OKTA_OAUTH2_AUDIENCE=
      - CLIENT_ORIGIN_URL=http://localhost:4040
    networks:
      - authzero

networks:
  authzero:
